### ISSUE TITLE
About permissions issue

### ISSUE THREAD

**Issue by maomc** [LostTeam/LostPets#11]
# nice plugin,But I entered the game instructs the display does not have permission to use this command

**Comment by GlitchPlayer** [comment]
What's your perms plugin?

**Comment by GlitchPlayer** [comment]
Make sure your an op because this plugin is designed for servers with ranking like VIP's

**Comment by maomc** [comment]
Ordinary players can receive it?

**Comment by maomc** [comment]
[23:55:32] [Server thread/CRITICAL]: Could not execute task LostTeam\task\PetsTick: Undefined index: weifeng
[23:55:32] [Server thread/NOTICE]: ArrayOutOfBoundsException: "Undefined index: weifeng" (E_NOTICE) in "/Pets_v0.7.0_BETA.phar/src/LostTeam/Main" at line 323

**Comment by jasonwynn10** [comment]
1. What type of server are you running?
2. the issue is known

**Comment by GlitchPlayer** [comment]
OP = Operator

**Comment by maomc** [comment]
Survival server, without any pre-plan is OP and VIP

**Comment by jasonwynn10** [comment]
I may be of assistance if I can join the server. what is the IP and Port?

**Comment by FuxonPlayz** [comment]
i have this problem as will
im using PurePerms For Permissions

**Comment by GlitchPlayer** [comment]
@FuxonPlayz do /setgperm {group} pets.command or /setpperm {player} pets.command

**Comment by FuxonPlayz** [comment]
@GlitchPlayer ive already did before posting and still not working i enter even children permission xD

**Comment by FuxonPlayz** [comment]
@GlitchPlayer Any Way im Changing My Perms Plugins

**Comment by GlitchPlayer** [comment]
If your rank has colors, maybe you mistyped it.

**Comment by GlitchPlayer** [comment]
@FuxonPlayz Ok then, I will now close this issue. If still not works for you. We kindly reopen this issue.
