### ISSUE TITLE
Feature Request: Adding Pet Type

### ISSUE THREAD

**Issue by FuxonPlayz** [LostTeam/LostPets#12]
Hi LostTeam,

Can u Please Add Pets Type Like
/pet type blaze

**Comment by GlitchPlayer** [comment]
If jasonwynn accepts, I can add. In my recent commits, I added types command.

**Comment by jasonwynn10** [comment]
It can be made possible after we fix the way mobs like the blaze are moving. Currently, the blaze doesn't fly and is slowed down a lot.

**Comment by GlitchPlayer** [comment]
Maybe we can start adding this feature except adding the unusable mobs
