### ISSUE TITLE
0.15.0 New Issue

### ISSUE THREAD

**Issue by GlitchPlayer** [LostTeam/LostPets#14]
- [x] This issue isn't related to third party builds of PocketMine
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description
Warning: in_array() expects parameter 2 to be array, string given in C:\Users\glitc\Documents\DarkPvP Network\plugins\LostPets-master\src\LostTeam\task\PetsTick.php on line 29

This gives a warning in line 29 that expects parameter 2 to be an array. But instead, string was given

Also, I believed the plugin causes that creative players can go through blocks. Just tested earlier

## Reproducing the issue
Download the 0.7.0 release phar.
Run the server.
You notice there will be a warning console log

## Client information
Version: 0.7.0 Beta Release
PHP: 7
OS: Windows 10

## Optional information
Warning: in_array() expects parameter 2 to be array, string given in C:\Users\glitc\Documents\DarkPvP Network\plugins\LostPets-master\src\LostTeam\task\PetsTick.php on line 29

**Comment by jasonwynn10** [comment]
is this pocketmine or a third party build?

**Comment by GlitchPlayer** [comment]
New error
Warning: in_array() expects parameter 2 to be array, null given in phar://C:/Users/glitc/Documents/DarkPvP Network/plugins/Pets_v0.8.1_BETA.phar/src/LostTeam/task/PetsTick.php on line 29

Sorry, I don't have time to fix right now :/

**Comment by jasonwynn10** [comment]
I found the issue, don't worry.It was just a typo

**Comment by GlitchPlayer** [comment]
Seems fixed.

Closing
