### ISSUE TITLE
mobs don't move the way they are supposed to

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/LostPets#5]
- [ ] Blaze
 - [ ] Rabbit
 - [ ] Bat
 - [ ] Magma Cube
 - [ ] Slime

Those mobs need movement fixes

**Comment by GlitchPlayer** [comment]
They move great on php7

**Comment by GlitchPlayer** [comment]
Tell Lucy, he knows

**Comment by jasonwynn10** [comment]
Blaze won't fly, rabbit doesn't hop, Bat hovers no wing flapping, Magme Cubedoesn't hop

**Comment by jasonwynn10** [comment]
Another thing: why do we have to have all the pets move at their normal mob speeds? Can I just set a speed for each mob?

**Comment by GlitchPlayer** [comment]
Yes, you can set each speed for pets

**Comment by jasonwynn10** [comment]
I'm going to set all the speeds to 1,2

**Comment by GlitchPlayer** [comment]
kk

**Comment by MCPEPIG** [comment]
What about slimes?

**Comment by GlitchPlayer** [comment]
Mhm. Your right. We add them too

**Comment by jasonwynn10** [comment]
then they will need a jumping movement
