### ISSUE TITLE
only first player to join can have a pet

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/LostPets#9]
After every restart, only the first player that joins can have a pet. the commands fail for everyone else

**Comment by GlitchPlayer** [comment]
Pretty sure that theres a code missing. I still have old php7 of Pets and
Everyone could use it

**Comment by jasonwynn10** [comment]
I need to update the version for php5

**Comment by GlitchPlayer** [comment]
By the way, could you turn on debug mode?

**Comment by jasonwynn10** [comment]
it should be on already...

**Comment by GlitchPlayer** [comment]
hm...

**Comment by GlitchPlayer** [comment]
Tested again on my server. This seems fixed

**Comment by GlitchPlayer** [comment]
Closing...
